#!/bin/sh

set -eu

. flags ${@:1}

# "Include" GameController source code as a C header with `xxd`
mkdir -p include/xxd
cd include/xxd
rm -rf *
cd .. # .../include
# ext/GameController/resources/config/spl/teams.cfg
echo '#ifndef XXD_GC_TEAM_CFG_HPP' > xxd/gc_team_cfg.hpp
echo '#define XXD_GC_TEAM_CFG_HPP' >> xxd/gc_team_cfg.hpp
echo '#pragma clang diagnostic push' >> xxd/gc_team_cfg.hpp
echo '#pragma clang diagnostic ignored "-Wreserved-identifier"' >> xxd/gc_team_cfg.hpp
echo '#define ___ext_GameController_resources_config_spl_teams_cfg constexpr inline static gc_team_cfg' >> xxd/gc_team_cfg.hpp # a dirty lil trick
echo '#define ___ext_GameController_resources_config_spl_teams_cfg_len constexpr inline static gc_team_cfg_len' >> xxd/gc_team_cfg.hpp
echo 'namespace xxd {' >> xxd/gc_team_cfg.hpp
xxd -i ../ext/GameController/resources/config/spl/teams.cfg >> xxd/gc_team_cfg.hpp
echo '} // namespace xxd' >> xxd/gc_team_cfg.hpp
echo '#undef ext_GameController_resources_config_spl_teams_cfg_len' >> xxd/gc_team_cfg.hpp
echo '#undef ext_GameController_resources_config_spl_teams_cfg' >> xxd/gc_team_cfg.hpp # undoing the low-down dirty rotten no-good trick
echo '#pragma clang diagnostic pop' >> xxd/gc_team_cfg.hpp
echo '#endif // XXD_GC_TEAM_CFG_HPP' >> xxd/gc_team_cfg.hpp
cd .. # back to where we were

clang++ -o bin/robocup-${EXECNAME} start.cpp ${@:5} ${MACROS} ${COMMON} ${WARNINGS} ${FLAGS}
