name: Basic C++ Safety Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checks
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-14-dev libclang-14-dev clang-14
        sh -x ./check --nofix --clang-version=14
        sh -x ./compile --debug --player2 --gc$(ifconfig | grep 'inet ' | grep -v '127\.0\.0\.1' | head -n 1 | cut -d 't' -f 2 | cut -d ' ' -f 2)
        sh -x ./compile --release --player2 --gc$(ifconfig | grep 'inet ' | grep -v '127\.0\.0\.1' | head -n 1 | cut -d 't' -f 2 | cut -d ' ' -f 2)
