name: Basic C++ Safety Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prereqs
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: check
      run: ./check
    - name: debug-build
      run: ./compile --debug --player2 --gc$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | cut -dt -f2 | cut -d\  -f2)
    - name: release-build
      run: ./compile --release --player2 --gc$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | cut -dt -f2 | cut -d\  -f2)
