name: Basic C++ Safety Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checks
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-14 llvm-14-dev llvm-14-runtime llvm-14-tools clang-14 libclang-14-dev
        cd ext/iwyu
        git fetch --all
        git checkout clang_14
        cd ../..
        ./check
        ./compile --debug --player2 --gc$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | cut -dt -f2 | cut -d\  -f2)
        ./compile --release --player2 --gc$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | cut -dt -f2 | cut -d\  -f2)
